name: flutter_mysite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.1.0
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  flutter_i18n: ^0.20.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  http: ^0.12.2
  logging: ^0.11.4
  material_design_icons_flutter: ^4.0.5655
  path_provider: ^1.6.21
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  bpw_common:
    path: packages/bpw_common
  bpw_renderer:
    path: packages/bpw_renderer
  bpw_wcm:
    path: packages/bpw_wcm
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    #i18n
    - assets/i18n_namespace/en/
    - assets/i18n_namespace/fr/
    - assets/i18n_namespace/zh/

    #site configurations
    - assets/sites/

    #Logo
    - assets/logo/logo.png

    #Images
    - assets/product/product-1.jpg
    - assets/product/product-2.jpg
    - assets/product/product-3.jpg
    - assets/product/product-4.jpg
    - assets/product/product-5.jpg
    - assets/product/product-6.jpg
    - assets/product/product-7.jpg
    - assets/product/product-8.jpg
    - assets/product/product-9.jpg
    - assets/product/product-10.jpg
    - assets/product/product-11.jpg

    #Camera
    - assets/product/camera/camera-1.jpg
    - assets/product/camera/camera-2.jpg
    - assets/product/camera/camera-3.jpg

    #Illusrtations
    - assets/illustration/illu-1.png
    - assets/illustration/illu-2.png
    - assets/illustration/illu-3.png
    - assets/illustration/illu-4.png
    - assets/illustration/illu-5.png
    - assets/illustration/illu-6.png
    - assets/illustration/empty-cart.png
    - assets/illustration/order-confirm.png
    - assets/illustration/error-503.png
    - assets/illustration/maintenance.png
    - assets/illustration/page-not-found.png
    - assets/illustration/sad.png

    #Profile-avatar
    - assets/profile/avatar.jpg
    - assets/profile/avatar-1.jpg
    - assets/profile/avatar-2.jpg
    - assets/profile/avatar-3.jpg
    - assets/profile/avatar-4.jpg
    - assets/profile/avatar-5.png
    - assets/profile/avatar-outline.png
    - assets/profile/avatar-outline-2.png

    #Company Logos
    - assets/brand/paypal.png
    - assets/brand/google.png

    #Vectos as PNG
    - assets/vector/dress.png
    - assets/vector/headphone.png
    - assets/vector/laptop.png
    - assets/vector/mobile.png
    - assets/vector/shoes.png
    - assets/vector/tshirt.png
    - assets/vector/watch.png

    #Other
    - assets/other/map-snap.png
    - assets/other/map-pin.png
    - assets/image/technology.jpg
    - assets/image/lifestyle.jpg
    - assets/image/fashion.jpg
    - assets/image/art.jpg
    - assets/image/offer-1.png
    - assets/image/offer-2.png

    # Custom Icons
    - assets/icons/albums-outline.png
    - assets/icons/rocket-outline.png
    - assets/icons/tablet-landscape-outline.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
